### ISSUE TITLE
Label Animation

### ISSUE THREAD

**Issue by melihbuyuk** [IgorVoiT/LettersBattleGame#1]
Hi @IgorVoiT,
How can I do the animation below? Could you show me an example of this?

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/304982/20937142/541f01f8-bbee-11e6-8f14-bcded7493328.gif)

I did not do a few trials, and finally I could not.

Thanks.
Melih.

**Comment by IgorVoiT** [comment]
Hi, Melih

Here's a little demo project, maybe you will find answer here!



2016-12-06 19:59 GMT+02:00 Melih Buyukbayram <notifications@github.com>:

**Comment by IgorVoiT** [comment]
[AnimTEST.zip](https://github.com/IgorVoiT/LettersBattleGame/files/636804/AnimTEST.zip)

**Comment by melihbuyuk** [comment]
Thanks Igor :)

**Comment by IgorVoiT** [comment]
No problem)
